local_knowledge/models.py
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import UserMixin, AnonymousUserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

db = SQLAlchemy()


class User(db.Model, UserMixin):
    id = db.Column(db.Integer(), primary_key=True)
    username = db.Column(db.String())
    password = db.Column(db.String())

    def __init__(self, username, password):
        self.username = username
        self.set_password(password)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, value):
        return check_password_hash(self.password, value)

    def is_authenticated(self):
        if isinstance(self, AnonymousUserMixin):
            return False
        else:
            return True

    def is_active(self):
        return True

    def is_anonymous(self):
        if isinstance(self, AnonymousUserMixin):
            return True
        else:
            return False

    def get_id(self):
        return self.id

    def __repr__(self):
        return '<User %r>' % self.username


class Node(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    osm_id = db.Column(db.BigInteger(), index=True, unique=True)
    geom = db.Column(Geometry('POINT', 4326))
    json = db.Column(postgresql.JSONB)
    created = db.Column(db.DateTime())
    updated = db.Column(db.DateTime())


class Way(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    osm_id = db.Column(db.BigInteger(), index=True, unique=True)
    geom = db.Column(Geometry('LINESTRING', 4326))
    name = db.Column(db.String())
    json = db.Column(postgresql.JSONB)
    created = db.Column(db.DateTime())
    updated = db.Column(db.DateTime())

local_knowledge/forms.py
from flask_wtf import Form
from wtforms import StringField, PasswordField
from wtforms import validators

from local_knowledge.models import User


class LoginForm(Form):
    username = StringField(u'Username', validators=[validators.required()])
    password = PasswordField(u'Password', validators=[validators.optional()])

    def validate(self):
        check_validate = super(LoginForm, self).validate()

        # if our validators do not pass
        if not check_validate:
            return False

        # Does our the exist
        user = User.query.filter_by(username=self.username.data).first()
        if not user:
            self.username.errors.append('Invalid username or password')
            return False

        # Do the passwords match
        if not user.check_password(self.password.data):
            self.username.errors.append('Invalid username or password')
            return False

        return True

local_knowledge/__init__.py
#! ../env/bin/python
# -*- coding: utf-8 -*-

__author__ = 'Alex Kerney'
__email__ = 'abk@mac.com'
__version__ = '0.1'

from flask import Flask
from webassets.loaders import PythonLoader as PythonAssetsLoader

from local_knowledge.controllers.main import main
from local_knowledge.controllers.api01 import api as api01
from local_knowledge import assets
from local_knowledge.models import db
from local_knowledge.tasks import celery

from local_knowledge.extensions import (
    cache,
    assets_env,
    debug_toolbar,
    login_manager
)


def create_app(object_name):
    """
    An flask application factory, as explained here:
    http://flask.pocoo.org/docs/patterns/appfactories/

    Arguments:
        object_name: the python path of the config object,
                     e.g. local_knowledge.settings.ProdConfig

        env: The name of the current environment, e.g. prod or dev
    """

    app = Flask(__name__)

    app.config.from_object(object_name)

    # initialize the cache
    cache.init_app(app)

    # initialize the debug tool bar
    debug_toolbar.init_app(app)

    # initialize SQLAlchemy
    db.init_app(app)

    # initialze celery
    celery.conf.update(app.config)

    login_manager.init_app(app)

    # Import and register the different asset bundles
    assets_env.init_app(app)
    assets_loader = PythonAssetsLoader(assets)
    for name, bundle in assets_loader.load_bundles().items():
        assets_env.register(name, bundle)

    # register our blueprints
    app.register_blueprint(main)
    app.register_blueprint(api01, url_prefix='/api/0.1')

    return app

local_knowledge/controllers/api01.py
""" Version 0.1 of api returning GeoJSON """
from flask import Blueprint, jsonify
from sqlalchemy import JSON

from local_knowledge.models import db, Way, Node

api = Blueprint('api', __name__)


@api.route('/nodes')
def nodes():
    """ Returns a GeoJSON Feature collection with all nodes """
    results = db.session.query(Node.id, Node.json, Node.geom.ST_AsGeoJSON().cast(JSON).label('geom')).all()
    
    features = {"type": "FeatureCollection",
                "features": [{'type': 'Feature',
                              'geometry': res.geom,
                              'properties': {'id': res.id,
                                             'osm_data': {k:res.json[k] for k in res.json if k != 'nd'}
                }} for res in results]}

    return jsonify(features)


@api.route('/ways')
def ways():
    """ Returns a GeoJSON Feature collection with all ways """
    results = db.session.query(Way.id, Way.name, Way.json, Way.geom.ST_AsGeoJSON().cast(JSON).label('geom')).all()
    fc = {
        'type': 'FeatureCollection',
        'features': [{'type': 'Feature',
                      'geometry': res.geom,
                      'properties' :{'id': res.id,
                                     'name': res.name,
                                      'osm_data': {k: res.json[k] for k in res.json
                                                   if k != 'linestring' and k != 'nd'} 
        }} for res in results]
    }
    return jsonify(fc)

local_knowledge/controllers/main.py
from flask import Blueprint, render_template, flash, request, redirect, url_for
from flask.ext.login import login_user, logout_user, login_required

from local_knowledge.extensions import cache
from local_knowledge.forms import LoginForm
from local_knowledge.models import User
from local_knowledge.settings import Config

main = Blueprint('main', __name__)


@main.route('/')
@cache.cached(timeout=1000)
def home():
    return render_template('index.html', 
                           MAPBOX_TOKEN=Config.MAPBOX_TOKEN,
                           MAPBOX_USER=Config.MAPBOX_USER)


@main.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).one()
        login_user(user)

        flash("Logged in successfully.", "success")
        return redirect(request.args.get("next") or url_for(".home"))

    return render_template("login.html", form=form)


@main.route("/logout")
def logout():
    logout_user()
    flash("You have been logged out.", "success")

    return redirect(url_for(".home"))


@main.route("/restricted")
@login_required
def restricted():
    return "You can only see this if you are logged in!", 200

local_knowledge/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        {% block meta %}
            <meta name="description" content="">
            <meta name="author" content="">
        {% endblock %}

        {% assets "common_css" %}
            <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}" />
        {% endassets %}

        {% block css %}
        {% endblock %}
    </head>

    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Local Knowledge</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('.home') }}">Home</a></li>

                    {% if not current_user.is_authenticated %}
                        <li><a href="{{ url_for('.login') }}">Login</a></li>
                    {% else %}
                        <li><a href="{{ url_for('.logout') }}">Logout</a></li>
                    {% endif %}

                    <li><a href="{{ url_for('.restricted') }}">Login Restricted Page</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>

        <div class="container">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }} alert-dismissible" role="alert">
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                          {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {% block body %}
            {% endblock %}
        </div>

        {% assets "common_js" %}
            <script type="text/javascript" src="{{ ASSET_URL }}"></script>
        {% endassets %}

        {% block js %}
        {% endblock %}
    </body>
</html>

local_knowledge/templates/index.html
{%extends "base.html"%}

{%block title%}Home{% endblock %}

{%block css %}
<script src='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.js'></script>
<link href='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.css' rel='stylesheet' />
{%endblock%}

{%block body%}
    <div class="jumbotron">
        <h1>Local Knowledge</h1>
    </div>

    <div class="row">
        <div class="col-md-8">
            <h3>Map</h3>
            <div id='map' style='width: 100%; height: 500px'></div>
        </div>
        <div class="col-md-4">
            <h4>Sidebar</h4>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h3>MVC Structure</h3>
            <p>While there are many other flask templates out there, far too many are either structured poorly or are tied down to a specific method of deployment, or both.</p>
            <p>So Flask Foundation has a best practices setup with blueprints and SQLAlchemy models that will allow you to grow cleanly</p>
        </div>

        <div class="col-md-4">
            <h3>Flask Extensions</h3>
            <p>Several flask extensions are included to handle the common tasks of web developers. The included extensions are flask-login, flask-assets, flask-WTF, flask-cache, flask-script, and flask-sqlalchemy.</p>
        </div>

        <div class="col-md-4">
            <h3>Management Scripts</h3>
            <p>Using the Makefile, you can easily setup your development environment with a few simple commands. With the power of flask-script you can create your own commands with the flask app context setup for you.</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h3>Tests</h3>
            <p>Example tests, built with py.test, are included in to demonstrate how to test a flask app.</p>
        </div>

        <div class="col-md-4">
            <h3>Common Libraries</h3>
            <p>The CSS Library Bootstrap is included, along with the Javascript libraries modernizr and jQuery.</p>
        </div>
    </div>
    <script>
        L.mapbox.accessToken = '{{ MAPBOX_TOKEN }}';

        var map = L.mapbox.map('map', '{{ MAPBOX_USER }}');

        var ways = L.mapbox.featureLayer().addTo(map);
        ways.loadURL('{{ url_for("api.ways") }}');
        ways.on('ready', function() {
            map.fitBounds(ways.getBounds());
        });
        
        
    </script>
{%endblock%}

local_knowledge/templates/login.html
{%extends "base.html" %}

{%block title %}Flask Login Example{% endblock %}

{%block body %}
    <h1 class="text-center">Flask Login Example</h1>

    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <form role="form"
                  action="{{ url_for('.login', next=request.args.get('next')) }}"
                  method="post"
                  enctype="multipart/form-data">
                {{ form.hidden_tag() }}

                <div class="form-group">
                    {{ form.username.label }}
                    {% if form.username.errors %}
                        {% for e in form.username.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.username(class_="form-control") }}
                </div>
                <div class="form-group">
                    {{ form.password.label }}
                    {% if form.password.errors %}
                        {% for e in form.password.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.password(class_="form-control") }}
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>
{%endblock %}